# Generated by Django 4.2.2 on 2023-06-29 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobileappp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parti_politique',
            name='fondateur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mobileappp.fondateur'),
            preserve_default=False,
        ),
    ]
