# Generated by Django 4.2.2 on 2023-06-30 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobileappp', '0002_parti_politique_fondateur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id_membre', models.AutoField(primary_key=True, serialize=False)),
                ('matricule', models.TextField(max_length=150)),
                ('identiter', models.TextField(max_length=150)),
                ('sexe', models.TextField(max_length=150)),
                ('etat_civil', models.TextField(max_length=150)),
                ('lieu_N', models.TextField(max_length=150)),
                ('date_N', models.DateField()),
                ('N_parcel', models.TextField(max_length=150)),
                ('avenue', models.TextField(max_length=150)),
                ('profession', models.TextField(max_length=150)),
                ('niveau_Etu', models.TextField(max_length=150)),
                ('niveau_membre', models.TextField(max_length=150)),
                ('tel', models.TextField(max_length=150)),
                ('email', models.TextField(max_length=150)),
                ('date_Ajout', models.DateField()),
                ('photo_membre', models.ImageField(upload_to='membre_img')),
            ],
            options={
                'db_table': 't_membre',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.TextField(max_length=50)),
                ('password', models.TextField(max_length=50)),
                ('staff', models.TextField(max_length=50)),
            ],
            options={
                'db_table': 't_user',
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id_story', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='story_img')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobileappp.user')),
            ],
            options={
                'db_table': 't_story',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id_post', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.TextField(max_length=150)),
                ('image_post', models.ImageField(upload_to='post_img')),
                ('other', models.TextField(max_length=150)),
                ('like', models.TextField(max_length=150)),
                ('commentaire', models.TextField(max_length=150)),
                ('description', models.TextField(max_length=150)),
                ('date_pub', models.DateField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobileappp.user')),
            ],
            options={
                'db_table': 't_post',
            },
        ),
    ]
