# Generated by Django 4.2.3 on 2023-07-17 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categoriePost',
            fields=[
                ('id_categorie', models.AutoField(primary_key=True, serialize=False)),
                ('categorie', models.TextField()),
            ],
            options={
                'db_table': 't_categorie',
            },
        ),
        migrations.CreateModel(
            name='commnetaire',
            fields=[
                ('id_commentaire', models.AutoField(primary_key=True, serialize=False)),
                ('commnetaire', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.TextField()),
            ],
            options={
                'db_table': 't_commentaire',
            },
        ),
        migrations.CreateModel(
            name='Fondateur',
            fields=[
                ('id_fondateur', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.TextField(max_length=50)),
                ('postnom', models.TextField(max_length=50)),
                ('prenom', models.TextField(max_length=50)),
                ('dateN', models.DateField()),
                ('photo', models.ImageField(upload_to='photo_fondateur')),
                ('description', models.TextField(max_length=500)),
            ],
            options={
                'db_table': 't_fondateur',
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id_story', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='story_img')),
                ('titre', models.TextField(max_length=30)),
            ],
            options={
                'db_table': 't_story',
            },
        ),
        migrations.CreateModel(
            name='video',
            fields=[
                ('id_video', models.AutoField(primary_key=True, serialize=False)),
                ('video', models.TextField()),
                ('image', models.ImageField(upload_to='image_video')),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 't_video',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id_post', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.TextField(max_length=150)),
                ('username', models.TextField()),
                ('image_post', models.ImageField(upload_to='post_img')),
                ('other', models.ImageField(upload_to='post_img')),
                ('like', models.IntegerField()),
                ('description', models.TextField(max_length=150)),
                ('date_pub', models.DateField(auto_now=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsapp.categoriepost')),
                ('commentaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsapp.commnetaire')),
            ],
            options={
                'db_table': 't_post',
            },
        ),
    ]
